// Package vector implements msgvault's semantic and hybrid search over
// the email corpus. Embeddings are generated by an external
// OpenAI-compatible endpoint; vectors are stored in a separate
// ~/.msgvault/vectors.db. See docs/superpowers/specs/2026-04-19-vector-search-design.md.
package vector

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// EmbeddingAPIFormat selects the request and response contract used by the
// configured embedding endpoint.
type EmbeddingAPIFormat string

const (
	// APIFormatOpenAI uses the OpenAI-compatible embeddings contract.
	APIFormatOpenAI EmbeddingAPIFormat = "openai"
	// APIFormatVoyageContextual uses Voyage contextualized embeddings.
	APIFormatVoyageContextual EmbeddingAPIFormat = "voyage-contextual"
	// contextPolicyVersion identifies the contextual document assembly policy.
	contextPolicyVersion = 2
	// Task prefixes are short provider instructions, not document content.
	// Bounding them prevents one prefix from exhausting contextual request
	// budgets before any source text can be assembled.
	maxEmbeddingTaskPrefixUTF8Bytes = 4096
)

// preprocessVersion identifies the embed/preprocess.go implementation
// generation. Bump whenever a change to that file produces a different
// Preprocess() output for the same PreprocessConfig flags — for
// example: tightening a regex, adding a tracking-param key, or adding
// a new default-on transform. Combined with the effective flag tuple
// in PreprocessConfig.Fingerprint, it makes Config.GenerationFingerprint
// invalidate any index built under a different preprocessing policy so
// the operator must --full-rebuild rather than silently mixing
// inconsistently-prepared vectors in one generation.
const preprocessVersion = 1

// embedPolicyVersion identifies the embed-worker output layout for a
// given Preprocess result. Bump whenever a change to internal/vector/
// embed/worker.go (or its chunking helpers) would shift the set of
// vectors written for the same Preprocess output — for example: the
// switch from single-vector-per-message to multi-chunk-per-message, a
// change to the chunk window/overlap derivation, or a change to the
// per-message chunk cap. Like preprocessVersion this is folded into
// GenerationFingerprint so flipping the policy stales the active
// index and forces --full-rebuild rather than mixing single-vector
// and chunked entries inside one generation.
//
// v1: chunked layout (the worker passes maxChars=0 to Preprocess and
// splits the result into MaxInputChars-bounded chunks via ChunkText).
const embedPolicyVersion = 1

const (
	defaultMultimodalEndpoint           = "https://api.voyageai.com/v1"
	multimodalProviderAPIVersion        = 1
	multimodalRoleMapVersion            = 1
	multimodalSignatureAllowlistVersion = 1
	multimodalContextPolicyVersion      = 1
	multimodalInputPolicyVersion        = 1
	// v2: eligibility moved to docbank media detection plus per-capability
	// probed upload authority; still GIFs became independently eligible.
	multimodalEligibilityPolicyVersion = 2

	// Animated GIFs stay off unless the operator both opts in and supplies a
	// manifest whose probe authorized them.
	multimodalAnimatedGIFDefault = false
)

var environmentVariableName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// Config is the top-level vector-search configuration, loaded from the
// [vector] TOML table.
type Config struct {
	Enabled    bool             `toml:"enabled"`
	Backend    string           `toml:"backend"` // "sqlite-vec" or "pgvector"; concrete backend is DSN-selected
	DBPath     string           `toml:"db_path"` // backend-specific
	Embeddings EmbeddingsConfig `toml:"embeddings"`
	Preprocess PreprocessConfig `toml:"preprocess"`
	Search     SearchConfig     `toml:"search"`
	Embed      EmbedConfig      `toml:"embed"`
	Multimodal MultimodalConfig `toml:"multimodal"`
	People     PeopleConfig     `toml:"people"`

	// SkipExtensionCreate skips the `CREATE EXTENSION IF NOT EXISTS
	// vector` step on the pgvector backend while still letting Migrate
	// create the schema tables and indexes. Set this on a managed or
	// locked-down PostgreSQL where the `vector` extension is installed by
	// an administrator and the msgvault role lacks the superuser privilege
	// CREATE EXTENSION requires. Ignored on the sqlite-vec backend.
	SkipExtensionCreate bool `toml:"skip_extension_create"`
}

// MultimodalConfig is an independently enabled hosted visual-embedding lane.
// Pointer booleans preserve the difference between an omitted option (use the
// checked-in capability default) and an explicit operator opt-out.
type MultimodalConfig struct {
	Enabled   bool   `toml:"enabled"`
	Provider  string `toml:"provider"`
	Endpoint  string `toml:"endpoint"`
	APIKeyEnv string `toml:"api_key_env"`
	Model     string `toml:"model"`
	Dimension int    `toml:"dimension"`
	// CapabilitiesFile is the operator-probed Voyage capability manifest.
	// Uploads fail closed without it.
	CapabilitiesFile    string              `toml:"capabilities_file"`
	MaxContextChars     int                 `toml:"max_context_chars"`
	IncludeImages       *bool               `toml:"include_images"`
	IncludeAnimatedGIFs *bool               `toml:"include_animated_gifs"`
	IncludeVideo        *bool               `toml:"include_video"`
	AllowImageQueries   *bool               `toml:"allow_image_queries"`
	Scope               EmbedScopeConfig    `toml:"scope"`
	Schedule            EmbedScheduleConfig `toml:"schedule"`
}

func configuredBool(value *bool, defaultValue bool) bool {
	if value == nil {
		return defaultValue
	}
	return *value
}

// ConfiguredImages and its siblings report the configured (default-resolved)
// consent values independent of Multimodal.Enabled, for settings surfaces
// that must show what WOULD take effect when the lane is enabled. Runtime
// gating uses ImagesEnabled and friends, which also require Enabled.
func (m MultimodalConfig) ConfiguredImages() bool       { return m.configuredImages() }
func (m MultimodalConfig) ConfiguredAnimatedGIFs() bool { return m.configuredAnimatedGIFs() }
func (m MultimodalConfig) ConfiguredVideo() bool        { return m.configuredVideo() }
func (m MultimodalConfig) ConfiguredImageQueries() bool { return m.configuredImageQueries() }

func (m MultimodalConfig) configuredImages() bool {
	return configuredBool(m.IncludeImages, true)
}

func (m MultimodalConfig) configuredAnimatedGIFs() bool {
	return configuredBool(m.IncludeAnimatedGIFs, multimodalAnimatedGIFDefault)
}

func (m MultimodalConfig) configuredVideo() bool {
	return configuredBool(m.IncludeVideo, true)
}

func (m MultimodalConfig) configuredImageQueries() bool {
	return configuredBool(m.AllowImageQueries, true)
}

// ImagesEnabled reports effective runtime consent for still-image documents.
func (m MultimodalConfig) ImagesEnabled() bool {
	return m.Enabled && m.configuredImages()
}

// AnimatedGIFsEnabled reports effective runtime consent for animated GIFs.
func (m MultimodalConfig) AnimatedGIFsEnabled() bool {
	return m.Enabled && m.configuredAnimatedGIFs()
}

// VideoEnabled reports effective runtime consent for direct video documents.
func (m MultimodalConfig) VideoEnabled() bool {
	return m.Enabled && m.configuredVideo()
}

// ImageQueriesEnabled reports effective runtime consent for image queries.
func (m MultimodalConfig) ImageQueriesEnabled() bool {
	return m.Enabled && m.configuredImageQueries()
}

// APIKey resolves the configured key without making its presence an
// enablement signal. Callers must pass the independent enablement and consent
// gates before using the returned value.
func (m MultimodalConfig) APIKey() string {
	if m.APIKeyEnv == "" {
		return ""
	}
	return lookupEnv(m.APIKeyEnv)
}

// EmbeddingsConfig configures the external embedding endpoint used to convert
// message text into vectors.
type EmbeddingsConfig struct {
	APIFormat      EmbeddingAPIFormat `toml:"api_format"`
	Endpoint       string             `toml:"endpoint"`
	APIKeyEnv      string             `toml:"api_key_env"`
	Model          string             `toml:"model"`
	DocumentPrefix string             `toml:"document_prefix"`
	QueryPrefix    string             `toml:"query_prefix"`
	Dimension      int                `toml:"dimension"`
	BatchSize      int                `toml:"batch_size"`
	Timeout        time.Duration      `toml:"timeout"`
	MaxRetries     int                `toml:"max_retries"`
	MaxInputChars  int                `toml:"max_input_chars"`
	ETAWindow      int                `toml:"eta_window"`
}

// EffectiveAPIFormat returns the configured API format, defaulting to the
// legacy OpenAI-compatible contract when api_format is omitted.
func (e EmbeddingsConfig) EffectiveAPIFormat() EmbeddingAPIFormat {
	if e.APIFormat == "" {
		return APIFormatOpenAI
	}
	return e.APIFormat
}

// Validate checks embedding-provider settings without requiring the ordinary
// message-vector lane to be enabled. Document vectors use the same provider
// policy under their own enablement and consent controls.
func (e EmbeddingsConfig) Validate() error {
	switch e.EffectiveAPIFormat() {
	case APIFormatOpenAI, APIFormatVoyageContextual:
	default:
		return fmt.Errorf("vector.embeddings.api_format: unknown format %q (supported: %q, %q)",
			e.APIFormat, APIFormatOpenAI, APIFormatVoyageContextual)
	}
	if e.EffectiveAPIFormat() == APIFormatVoyageContextual && e.Model != "voyage-context-4" {
		return fmt.Errorf("vector.embeddings.model: api_format=%q requires %q, got %q",
			APIFormatVoyageContextual, "voyage-context-4", e.Model)
	}
	if e.Endpoint == "" {
		return errors.New("vector.embeddings.endpoint: required")
	}
	u, err := url.Parse(e.Endpoint)
	if err != nil || u.Host == "" || (u.Scheme != "http" && u.Scheme != "https") {
		return errors.New("vector.embeddings.endpoint: must be an http or https URL with a host")
	}
	if u.User != nil {
		return errors.New("vector.embeddings.endpoint: must not contain credentials")
	}
	if u.RawQuery != "" {
		return errors.New("vector.embeddings.endpoint: must not contain a query")
	}
	if u.Fragment != "" {
		return errors.New("vector.embeddings.endpoint: must not contain a fragment")
	}
	if e.Model == "" {
		return fmt.Errorf("vector.embeddings.model: required (the index generation fingerprint is %q, which is ambiguous without a model name)", e.Fingerprint())
	}
	if len(e.DocumentPrefix) > maxEmbeddingTaskPrefixUTF8Bytes {
		return fmt.Errorf("vector.embeddings.document_prefix: must be at most %d UTF-8 bytes, got %d",
			maxEmbeddingTaskPrefixUTF8Bytes, len(e.DocumentPrefix))
	}
	if len(e.QueryPrefix) > maxEmbeddingTaskPrefixUTF8Bytes {
		return fmt.Errorf("vector.embeddings.query_prefix: must be at most %d UTF-8 bytes, got %d",
			maxEmbeddingTaskPrefixUTF8Bytes, len(e.QueryPrefix))
	}
	if e.Dimension <= 0 {
		return fmt.Errorf("vector.embeddings.dimension: must be positive, got %d", e.Dimension)
	}
	if e.BatchSize <= 0 {
		return fmt.Errorf("vector.embeddings.batch_size: must be positive, got %d", e.BatchSize)
	}
	return nil
}

// PreprocessConfig controls message text preprocessing before embedding.
//
// Fields are pointers so the decoder can distinguish "unset" (nil,
// defaults to true) from an explicit `false` in the TOML file. Call the
// XxxEnabled helpers to resolve the effective value.
type PreprocessConfig struct {
	StripQuotes        *bool `toml:"strip_quotes"`
	StripSignatures    *bool `toml:"strip_signatures"`
	StripHTML          *bool `toml:"strip_html"`
	StripBase64        *bool `toml:"strip_base64"`
	StripURLTracking   *bool `toml:"strip_url_tracking"`
	CollapseWhitespace *bool `toml:"collapse_whitespace"`
}

// StripQuotesEnabled returns the effective strip_quotes setting.
// Defaults to true when the field is unset.
func (p PreprocessConfig) StripQuotesEnabled() bool {
	if p.StripQuotes == nil {
		return true
	}
	return *p.StripQuotes
}

// StripSignaturesEnabled returns the effective strip_signatures setting.
// Defaults to true when the field is unset.
func (p PreprocessConfig) StripSignaturesEnabled() bool {
	if p.StripSignatures == nil {
		return true
	}
	return *p.StripSignatures
}

// StripHTMLEnabled returns the effective strip_html setting.
// Defaults to true when the field is unset — HTML markup that leaks into
// body_text tokenizes densely (punctuation-heavy) without contributing
// semantic content.
func (p PreprocessConfig) StripHTMLEnabled() bool {
	if p.StripHTML == nil {
		return true
	}
	return *p.StripHTML
}

// StripBase64Enabled returns the effective strip_base64 setting.
// Defaults to true when the field is unset — inline base64 blobs (images,
// embedded MIME parts) inflate token counts without contributing
// retrievable meaning.
func (p PreprocessConfig) StripBase64Enabled() bool {
	if p.StripBase64 == nil {
		return true
	}
	return *p.StripBase64
}

// StripURLTrackingEnabled returns the effective strip_url_tracking setting.
// Defaults to true when the field is unset — utm_*, fbclid, etc. add no
// semantic value and make otherwise-identical URLs look distinct to the
// embedder.
func (p PreprocessConfig) StripURLTrackingEnabled() bool {
	if p.StripURLTracking == nil {
		return true
	}
	return *p.StripURLTracking
}

// CollapseWhitespaceEnabled returns the effective collapse_whitespace setting.
// Defaults to true when the field is unset — HTML→text conversion routinely
// produces runs of empty lines and double-spaces that crowd out real content
// under the max_input_chars cap.
func (p PreprocessConfig) CollapseWhitespaceEnabled() bool {
	if p.CollapseWhitespace == nil {
		return true
	}
	return *p.CollapseWhitespace
}

// Fingerprint returns a stable, debuggable identifier for the effective
// preprocessing policy. Format: "p<ver>-<flags>" where ver is the
// preprocessVersion constant (bumped on regex/policy changes inside
// internal/vector/embed/preprocess.go) and flags is a 0/1 string in
// field-declaration order: strip_quotes, strip_signatures, strip_html,
// strip_base64, strip_url_tracking, collapse_whitespace. New toggles
// append to the right so adding one cannot collide with an existing
// fingerprint by accident.
func (p PreprocessConfig) Fingerprint() string {
	flags := []bool{
		p.StripQuotesEnabled(),
		p.StripSignaturesEnabled(),
		p.StripHTMLEnabled(),
		p.StripBase64Enabled(),
		p.StripURLTrackingEnabled(),
		p.CollapseWhitespaceEnabled(),
	}
	var b strings.Builder
	b.Grow(len("p999-") + len(flags))
	fmt.Fprintf(&b, "p%d-", preprocessVersion)
	for _, on := range flags {
		if on {
			b.WriteByte('1')
		} else {
			b.WriteByte('0')
		}
	}
	return b.String()
}

// SearchConfig controls hybrid-search ranking and result limits.
//
// MaxPageSizeHybrid is a *int so an omitted field (nil) can be told
// apart from an explicit 0 in the TOML file. ApplyDefaults fills in
// 50 only when nil; explicit `max_page_size_hybrid = 0` is preserved
// and disables the per-request clamp entirely. Use the
// MaxPageSizeHybridClamp helper to read the effective value at the
// API/MCP boundary.
type SearchConfig struct {
	RRFK              int     `toml:"rrf_k"`
	KPerSignal        int     `toml:"k_per_signal"`
	SubjectBoost      float64 `toml:"subject_boost"`
	MaxPageSizeHybrid *int    `toml:"max_page_size_hybrid"`
}

// MaxPageSizeHybridClamp returns the effective per-request limit
// clamp: zero means "no clamp", a positive value means "clamp to N".
// Helper exists because callers want a flat int and need to handle
// the nil-pointer "unset" case identically to an explicit 0.
func (s SearchConfig) MaxPageSizeHybridClamp() int {
	if s.MaxPageSizeHybrid == nil {
		return 0
	}
	return *s.MaxPageSizeHybrid
}

// EmbedConfig groups embed-side concerns that aren't part of the
// embedding endpoint itself (e.g. scheduling).
type EmbedConfig struct {
	Schedule EmbedScheduleConfig `toml:"schedule"`
	// BackstopInterval is how often the daemon embed job also runs a full
	// watermark-ignoring backstop pass (recovering below-watermark
	// stragglers from repair-encoding resets, transient errors, or crashes)
	// in addition to the per-tick incremental scan. Zero uses the EmbedJob
	// default (24h); a negative value disables the auto-backstop.
	BackstopInterval time.Duration    `toml:"backstop_interval"`
	Scope            EmbedScopeConfig `toml:"scope"`
}

// EmbedScheduleConfig controls when the embed worker runs on its own
// (outside of explicit `msgvault embeddings build` invocations).
type EmbedScheduleConfig struct {
	Cron         string `toml:"cron"`           // empty disables scheduled embedding
	RunAfterSync bool   `toml:"run_after_sync"` // trigger after each successful sync
}

// EmbedScopeConfig limits which messages are included in newly-built
// embedding generations. The zero value means the full corpus.
type EmbedScopeConfig struct {
	MessageTypes []string `toml:"message_types"`
	// Accounts limits embedding to the given account identifiers (the same
	// syntax the --account flag accepts). Identifiers live in config rather
	// than source IDs so the file survives archive rebuilds that renumber
	// sources; the command layer resolves them to SourceIDs against the
	// open store at startup, where unknown identifiers are a hard error.
	Accounts []string `toml:"accounts"`
	// SourceIDs is the resolved form of Accounts (or of a CLI
	// --account/--collection override), filled in by the command layer
	// before the scope is used for building, coverage, or fingerprinting.
	// It is never read from TOML.
	SourceIDs []int64 `toml:"-"`
}

func (s EmbedScopeConfig) BuildScope() BuildScope {
	return NewBuildScope(s.MessageTypes, s.SourceIDs)
}

// Fingerprint returns the "<model>:<dimension>" identifier for the
// embedding endpoint half of the policy (§6.7 of the spec). Use
// Config.GenerationFingerprint when storing or comparing index
// generations — that variant also folds in the preprocessing policy so
// flipping a strip_* toggle stales the index.
func (e EmbeddingsConfig) Fingerprint() string {
	return fmt.Sprintf("%s:%d", e.Model, e.Dimension)
}

// GenerationFingerprint returns the full identifier used to compare an
// index generation against the configured policy. Format:
// "<model>:<dimension>:<preprocess>:c<max_input_chars>:e<embed_policy>".
// Non-empty document or query prefixes add a hashed ":t<digest>" segment.
// Contextual generations add
// ":avoyage-contextual:v<context_policy_version>" before any scope segment.
// Every segment is derived from the effective config (or a code-level
// version constant), so changing the embedding model/dimension, any
// preprocessing toggle, the truncation cap, or the embed-worker output
// layout produces a new fingerprint and the ResolveActiveForFingerprint
// check forces a --full-rebuild rather than silently embedding new
// messages under a policy different from the already-active vectors.
//
// max_input_chars is part of the policy because the embed worker uses
// it as the per-chunk rune cap fed into ChunkText (and, before
// chunking, as the rune-bounded truncation cap fed into Preprocess);
// raising or lowering it changes which chunks a long message produces,
// so two cap values produce two different embedding layouts and must
// not share one generation.
//
// Person renderer policy is deliberately excluded: it is part of every
// person document revision, so changing it rebuilds only the bounded person
// corpus instead of forcing a paid full-message generation rebuild.
//
// embed_policy (the embedPolicyVersion constant) covers worker-side
// changes that shift the vector layout for the same Preprocess output
// — most notably the switch from one-vector-per-message-with-truncation
// to N-vectors-per-message-via-ChunkText. Without folding this version
// in, an active generation built under the old single-vector policy
// would silently accept new chunked entries from an upgraded worker.
func (c *Config) GenerationFingerprint() string {
	fp := fmt.Sprintf("%s:%s:c%d:e%d",
		c.Embeddings.Fingerprint(), c.Preprocess.Fingerprint(), c.Embeddings.MaxInputChars,
		embedPolicyVersion)
	if taskPrefixFingerprint := c.Embeddings.TaskPrefixFingerprint(); taskPrefixFingerprint != "" {
		fp += ":t" + taskPrefixFingerprint
	}
	if c.Embeddings.EffectiveAPIFormat() == APIFormatVoyageContextual {
		fp = fmt.Sprintf("%s:a%s:v%d", fp, APIFormatVoyageContextual, contextPolicyVersion)
	}
	if scopeFP := c.Embed.Scope.BuildScope().Fingerprint(); scopeFP != "" {
		fp = fmt.Sprintf("%s:s%s", fp, scopeFP)
	}
	return fp
}

// TaskPrefixFingerprint identifies document/query task-prefix policy without
// exposing configured prefix text. Empty policy deliberately has no identity
// so existing generation fingerprints retain their exact legacy bytes.
func (e EmbeddingsConfig) TaskPrefixFingerprint() string {
	if e.DocumentPrefix == "" && e.QueryPrefix == "" {
		return ""
	}
	encoded := fmt.Sprintf("embedding-prefix-v1:%d:%s:%d:%s",
		len(e.DocumentPrefix), e.DocumentPrefix, len(e.QueryPrefix), e.QueryPrefix)
	digest := sha256.Sum256([]byte(encoded))
	return hex.EncodeToString(digest[:])
}

// AnyLaneEnabled reports whether either the ordinary text-vector lane or the
// independently consented multimodal lane requires vector infrastructure.
func (c *Config) AnyLaneEnabled() bool {
	return c.Enabled || c.Multimodal.Enabled
}

// MultimodalGenerationFingerprint identifies only model-input policy. It
// deliberately excludes the API-key environment variable, schedules, and the
// enabled switch so operational changes cannot force a paid rebuild. Provider
// API shape, normalized destination, model, media/context policy, and scope all
// participate.
func (c *Config) MultimodalGenerationFingerprint() string {
	endpoint, err := normalizedMultimodalEndpoint(c.Multimodal.Endpoint)
	if err != nil {
		endpoint = strings.TrimSpace(c.Multimodal.Endpoint)
	}
	segments := []string{
		fmt.Sprintf("provider-api-v%d", multimodalProviderAPIVersion),
		strings.ToLower(strings.TrimSpace(c.Multimodal.Provider)),
		endpoint,
		strings.TrimSpace(c.Multimodal.Model),
		strconv.Itoa(c.Multimodal.Dimension),
		fmt.Sprintf("role-map-v%d", multimodalRoleMapVersion),
		fmt.Sprintf("signature-allowlist-v%d", multimodalSignatureAllowlistVersion),
		fmt.Sprintf("preprocess-v%d", preprocessVersion),
		fmt.Sprintf("context-v%d", multimodalContextPolicyVersion),
		strconv.Itoa(c.Multimodal.MaxContextChars),
		fmt.Sprintf("input-v%d", multimodalInputPolicyVersion),
		fmt.Sprintf("eligibility-v%d", multimodalEligibilityPolicyVersion),
		strconv.FormatBool(c.Multimodal.configuredImages()),
		strconv.FormatBool(c.Multimodal.configuredAnimatedGIFs()),
		strconv.FormatBool(c.Multimodal.configuredVideo()),
		strconv.FormatBool(c.Multimodal.configuredImageQueries()),
		c.Multimodal.Scope.BuildScope().Fingerprint(),
	}
	digest := sha256.Sum256([]byte(strings.Join(segments, "\x1f")))
	return "visual-v1-" + hex.EncodeToString(digest[:])
}

// Validate returns a descriptive error if an enabled vector lane is unusable.
// Disabled lane-specific settings are retained without activating or
// validating hosted work.
func (c *Config) Validate() error {
	if !c.AnyLaneEnabled() {
		return nil
	}
	// The concrete backend is selected at the command layer from the
	// database DSN (SQLite → sqlite-vec, PostgreSQL → pgvector); this
	// field is a declared marker, not the selector. Accept either known
	// backend and reject anything else.
	switch c.Backend {
	case "sqlite-vec", "pgvector":
	default:
		return fmt.Errorf("vector.backend: unknown backend %q (supported: \"sqlite-vec\", \"pgvector\")", c.Backend)
	}
	if c.Multimodal.Enabled {
		if err := c.Multimodal.validate(); err != nil {
			return err
		}
	}
	if !c.Enabled {
		return nil
	}
	if err := c.Embeddings.Validate(); err != nil {
		return err
	}
	if c.People.Enabled {
		if _, err := c.SemanticPersonEmbeddingProfile(); err != nil {
			return err
		}
	}
	return nil
}

// Validate checks the multimodal lane settings without requiring the lane to
// be enabled. The capability probe runs before enablement and must confirm
// the provider and pinned destination before it reads or sends a credential.
func (m MultimodalConfig) Validate() error { return m.validate() }

func (m MultimodalConfig) validate() error {
	if m.Provider != "voyage" {
		return fmt.Errorf("vector.multimodal.provider: must be %q, got %q", "voyage", m.Provider)
	}
	normalizedEndpoint, err := normalizedMultimodalEndpoint(m.Endpoint)
	if err != nil {
		return fmt.Errorf("vector.multimodal.endpoint: %w", err)
	}
	if normalizedEndpoint != defaultMultimodalEndpoint {
		// The docbank transport pins the provider endpoint into the policy
		// identity that capability manifests and consent cover. A proxy or
		// alternate origin configured here would be silently ignored, so it
		// is refused instead.
		return fmt.Errorf("vector.multimodal.endpoint: only the pinned provider endpoint %s is supported (got %q)",
			defaultMultimodalEndpoint, m.Endpoint)
	}
	if m.APIKeyEnv == "" || !environmentVariableName.MatchString(m.APIKeyEnv) {
		return fmt.Errorf("vector.multimodal.api_key_env: must be a valid environment variable name, got %q", m.APIKeyEnv)
	}
	if m.Model != "voyage-multimodal-3.5" {
		return fmt.Errorf("vector.multimodal.model: must be %q, got %q", "voyage-multimodal-3.5", m.Model)
	}
	if m.Dimension != 1024 {
		return fmt.Errorf("vector.multimodal.dimension: must be 1024, got %d", m.Dimension)
	}
	if m.MaxContextChars <= 0 {
		return fmt.Errorf("vector.multimodal.max_context_chars: must be positive, got %d", m.MaxContextChars)
	}
	if !m.configuredImages() && !m.configuredAnimatedGIFs() && !m.configuredVideo() {
		return errors.New("vector.multimodal: at least one document media type must be enabled")
	}
	// Animated GIFs are an image subtype: the runtime media policy only
	// admits animated media when still images are enabled, so an
	// animated-only lane would reject every attachment yet still activate.
	if m.configuredAnimatedGIFs() && !m.configuredImages() {
		return errors.New("vector.multimodal.include_animated_gifs: requires include_images = true")
	}
	return nil
}

func normalizedMultimodalEndpoint(endpoint string) (string, error) {
	u, err := url.Parse(strings.TrimSpace(endpoint))
	if err != nil || u.Host == "" {
		return "", fmt.Errorf("must be an HTTPS URL with a host (got %q)", endpoint)
	}
	if strings.ToLower(u.Scheme) != "https" {
		return "", fmt.Errorf("must use HTTPS (got %q)", endpoint)
	}
	if u.User != nil || u.RawQuery != "" || u.Fragment != "" {
		return "", fmt.Errorf("must not contain credentials, query parameters, or a fragment (got %q)", endpoint)
	}
	path := strings.TrimRight(u.EscapedPath(), "/")
	if path != "/v1" {
		return "", fmt.Errorf("must end at the provider API root /v1 (got %q)", endpoint)
	}
	return "https://" + strings.ToLower(u.Host) + path, nil
}

// ApplyDefaults fills in sensible defaults for any zero-valued fields.
// Called after TOML decode, before Validate.
func (c *Config) ApplyDefaults() {
	if c.Backend == "" {
		c.Backend = "sqlite-vec"
	}
	if c.Embeddings.BatchSize == 0 {
		c.Embeddings.BatchSize = 32
	}
	if c.Embeddings.Timeout == 0 {
		c.Embeddings.Timeout = 30 * time.Second
	}
	if c.Embeddings.MaxRetries == 0 {
		c.Embeddings.MaxRetries = 3
	}
	if c.Embeddings.MaxInputChars == 0 {
		c.Embeddings.MaxInputChars = 32768
	}
	if c.Embeddings.ETAWindow <= 0 {
		c.Embeddings.ETAWindow = 10
	}
	if c.Search.RRFK == 0 {
		c.Search.RRFK = 60
	}
	if c.Search.KPerSignal == 0 {
		c.Search.KPerSignal = 100
	}
	if c.Search.SubjectBoost == 0 {
		c.Search.SubjectBoost = 2.0
	}
	if c.Search.MaxPageSizeHybrid == nil {
		v := 50
		c.Search.MaxPageSizeHybrid = &v
	}
	c.Multimodal.Provider = strings.ToLower(strings.TrimSpace(c.Multimodal.Provider))
	if c.Multimodal.Provider == "" {
		c.Multimodal.Provider = "voyage"
	}
	c.Multimodal.Endpoint = strings.TrimSpace(c.Multimodal.Endpoint)
	if c.Multimodal.Endpoint == "" {
		c.Multimodal.Endpoint = defaultMultimodalEndpoint
	}
	c.Multimodal.APIKeyEnv = strings.TrimSpace(c.Multimodal.APIKeyEnv)
	endpointIdentity, endpointErr := normalizedMultimodalEndpoint(c.Multimodal.Endpoint)
	if c.Multimodal.APIKeyEnv == "" && endpointErr == nil && endpointIdentity == defaultMultimodalEndpoint {
		c.Multimodal.APIKeyEnv = "VOYAGE_API_KEY"
	}
	c.Multimodal.Model = strings.TrimSpace(c.Multimodal.Model)
	if c.Multimodal.Model == "" {
		c.Multimodal.Model = "voyage-multimodal-3.5"
	}
	if c.Multimodal.Dimension == 0 {
		c.Multimodal.Dimension = 1024
	}
	if c.Multimodal.MaxContextChars == 0 {
		c.Multimodal.MaxContextChars = 4000
	}
	// Preprocess booleans are *bool so unset (nil) means "default true"
	// without overwriting an explicit false from the config file. The
	// StripQuotesEnabled / StripSignaturesEnabled helpers resolve the
	// effective value.
}

// APIKey resolves the API key from the env var named in APIKeyEnv.
// Returns "" if APIKeyEnv is empty or the variable is unset.
func (e EmbeddingsConfig) APIKey() string {
	if e.APIKeyEnv == "" {
		return ""
	}
	return lookupEnv(e.APIKeyEnv)
}
